<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BlogController extends Controller
{
    /**
     * Display all blogs
     */
    public function index()
    {
        $blogs = Blog::latest()->get();

        return response()->json([
            'status' => true,
            'data' => $blogs,
        ]);
    }

    public function indexShowBlogSlug($slug)
    {
        $blog = Blog::where('slug', $slug)->firstOrFail();

        return response()->json([
            'status' => true,
            'data' => $blog,
        ]);
    }

    /**
     * Store a new blog
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|string|max:255',
            'short_description' => 'required|string',
            'long_description' => 'required|string',
            'category' => 'required|string',
            'duration' => 'required|string',
            'image' => 'nullable|image|mimes:jpg,jpeg,png|max:2048',
        ]);

        // Handle image upload
        $imagePath = null;
        if ($request->hasFile('image')) {
            $imagePath = $request->file('image')->store('blogs', 'public');
        }

        // Let the model handle slug generation automatically
        $blog = Blog::create([
            'title' => $request->title,
            'short_description' => $request->short_description,
            'long_description' => $request->long_description,
            'category' => $request->category,
            'duration' => $request->duration,
            'image' => $imagePath,
            // Slug is automatically generated by the model's boot methods
        ]);

        return response()->json([
            'status' => true,
            'message' => 'Blog created successfully',
            'data' => $blog,
        ]);
    }

    /**
     * Display single blog
     */
    public function show($id)
    {
        $blog = Blog::findOrFail($id);

        return response()->json([
            'status' => true,
            'data' => $blog,
        ]);
    }

    /**
     * Update blog
     */
    public function update(Request $request, $id)
    {
        $blog = Blog::findOrFail($id);

        $request->validate([
            'title' => 'required|string|max:255',
            'short_description' => 'required|string',
            'long_description' => 'required|string',
            'category' => 'required|string',
            'duration' => 'required|string',
            'image' => 'nullable|image|mimes:jpg,jpeg,png|max:2048',
        ]);

        // Update image (delete old one if new uploaded)
        if ($request->hasFile('image')) {
            // Delete old image if exists
            if ($blog->image && Storage::disk('public')->exists($blog->image)) {
                Storage::disk('public')->delete($blog->image);
            }

            $blog->image = $request->file('image')->store('blogs', 'public');
        }

        // Update fields - let the model handle slug if title changes
        $blog->update([
            'title' => $request->title,
            'short_description' => $request->short_description,
            'long_description' => $request->long_description,
            'category' => $request->category,
            'duration' => $request->duration,
            'image' => $blog->image,
            // Don't manually set slug - the model will handle it if needed
        ]);

        return response()->json([
            'status' => true,
            'message' => 'Blog updated successfully',
            'data' => $blog,
        ]);
    }

    /**
     * Delete blog
     */
    public function destroy($id)
    {
        $blog = Blog::findOrFail($id);

        // Delete image from storage
        if ($blog->image && Storage::disk('public')->exists($blog->image)) {
            Storage::disk('public')->delete($blog->image);
        }

        $blog->delete();

        return response()->json([
            'status' => true,
            'message' => 'Blog deleted successfully',
        ]);
    }
}
